import type { NextPage } from 'next'
import { ChangeEvent, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import {
  Container,
  Main,
  Footer,
  Content,
  SwapIconContainer,
  Title,
} from '../styles/pages/home'
import { Form, Input } from 'antd'
import { SwapOutlined } from '@ant-design/icons'
import logo from '../../public/images/logo/neptune-mutual.svg'
import { cryptoConversion } from '../utils/utils'

const Home: NextPage = () => {
  const [fromCryptoCurrency, setFromCryptoCurrency] = useState(0)
  const [toCryptoCurrency, setToCryptoCurrency] = useState(0)

  function handleInputChange(
    e: ChangeEvent<HTMLInputElement>,
    type: string
  ): void {
    const currentValue = e.target.value
    const convertedValue = cryptoConversion(type, currentValue) // uses conversion utility to get the converted value

    if (type === 'NEP') {
      // set the current value to current crypto currency, set the converted value to other crypto currency vice versa
      setFromCryptoCurrency(Number(currentValue))
      setToCryptoCurrency(convertedValue)
    } else {
      setToCryptoCurrency(Number(currentValue))
      setFromCryptoCurrency(convertedValue)
    }
  }

  return (
    <Container>
      <Head>
        <title>Neptune Mutual - Crypto Converter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Image src={logo} alt="neptune mutual" />
        <Content>
          <Title>Crypto Converter</Title>
          <Form name="crypto-converter">
            <Form.Item noStyle>
              <Input
                placeholder="0.00"
                addonBefore="NEP"
                allowClear
                type="number"
                size="large"
                onChange={(e) => handleInputChange(e, 'NEP')}
                value={fromCryptoCurrency}
              />
            </Form.Item>
            <SwapIconContainer>
              <SwapOutlined style={{ fontSize: 20 }} />
            </SwapIconContainer>
            <Form.Item noStyle>
              <Input
                placeholder="0.00"
                addonBefore="BUSD"
                allowClear
                type="number"
                size="large"
                onChange={(e) => handleInputChange(e, 'BUSD')}
                value={toCryptoCurrency}
              />
            </Form.Item>
          </Form>
        </Content>
      </Main>

      <Footer>
        <p>Neptune Mutual &#169; 2022</p>
      </Footer>
    </Container>
  )
}

export default Home
